name: exam_platform
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  flutter_svg: ^2.2.0
  file_selector: ^1.1.0
  shared_preferences: ^2.5.5
  cloud_firestore: ^6.8.0
  firebase_core: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - content/
    - content/domain_07/competencies/

flutter_launcher_icons:
  android: true
  web:
    generate: true
    image_path: assets/icon/csp11_logo.png
    background_color: "#0B0F17"
    theme_color: "#0B0F17"
  image_path: assets/icon/csp11_logo.png
  adaptive_icon_background: "#0B0F17"
  adaptive_icon_foreground: assets/icon/csp11_logo.png
  min_sdk_android: 21