// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYU2eP55graBeFqCiyEMMEH2ATVePVS4',
    appId: '1:984608502679:web:4e575d4d91d14342ca0ad2',
    messagingSenderId: '984608502679',
    projectId: 'csp11-exam-platform',
    authDomain: 'csp11-exam-platform.firebaseapp.com',
    storageBucket: 'csp11-exam-platform.firebasestorage.app',
    measurementId: 'G-ZPEEX27RYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCawHUhwPkeb31XutbaewEA8AeGF89cG_c',
    appId: '1:984608502679:android:80cbdc69e27a54e5ca0ad2',
    messagingSenderId: '984608502679',
    projectId: 'csp11-exam-platform',
    storageBucket: 'csp11-exam-platform.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTYU2eP55graBeFqCiyEMMEH2ATVePVS4',
    appId: '1:984608502679:web:c77f1eb0e570105fca0ad2',
    messagingSenderId: '984608502679',
    projectId: 'csp11-exam-platform',
    authDomain: 'csp11-exam-platform.firebaseapp.com',
    storageBucket: 'csp11-exam-platform.firebasestorage.app',
    measurementId: 'G-EZTH45MTMR',
  );
}
