class DqgContractRule {
  final String id;
  final String title;

  const DqgContractRule(this.id, this.title);
}

const dqgContractRules = <DqgContractRule>[
  DqgContractRule('DQG-001', 'Exactly four options'),
  DqgContractRule('DQG-002', 'Exactly one valid BEST-answer key'),
  DqgContractRule('DQG-003', 'Exactly three matching distractors'),
  DqgContractRule('DQG-004', 'Question and distractors are DQ6'),
  DqgContractRule('DQG-005', 'Distractor plausibility exactly 5'),
  DqgContractRule('DQG-006', 'Truth component exactly 4'),
  DqgContractRule('DQG-007', 'Confusability exactly 4'),
  DqgContractRule('DQG-008', 'Computed DQS exactly 100'),
  DqgContractRule('DQG-009', 'No unresolved blocks'),
  DqgContractRule('DQG-010', 'No unresolved fails'),
  DqgContractRule('DQG-011', 'No unresolved warnings'),
  DqgContractRule('DQG-012', 'No publication override'),
  DqgContractRule('DQG-013', 'Exactly one defensible BEST answer'),
  DqgContractRule('DQG-014', 'Review complete'),
  DqgContractRule('DQG-015', 'Mandatory evidence complete'),
  DqgContractRule('DQG-016', 'Frozen thresholds exact'),
  DqgContractRule('DQG-017', 'Expert near-miss roles'),
  DqgContractRule('DQG-018', 'Same technical universe and level'),
  DqgContractRule('DQG-019', 'Substantial technical correctness'),
  DqgContractRule('DQG-020', 'Single fatal flaw'),
  DqgContractRule('DQG-021', 'No multiple unrelated defects'),
  DqgContractRule('DQG-022', 'Distinct failure mechanisms'),
  DqgContractRule('DQG-023', 'Unique misconception fingerprints'),
  DqgContractRule('DQG-024', 'Sophisticated credible reasoning'),
  DqgContractRule('DQG-025', 'Targeted misconception present'),
  DqgContractRule('DQG-026', 'Temptation rationale present'),
  DqgContractRule('DQG-027', 'Fatal-flaw explanation present'),
  DqgContractRule('DQG-028', 'Scenario anchors present and valid'),
  DqgContractRule('DQG-029', 'Technical truth documented'),
  DqgContractRule('DQG-030', 'Key difference documented'),
  DqgContractRule('DQG-031', 'Counterfactual documented'),
  DqgContractRule('DQG-032', 'Distractor family valid'),
  DqgContractRule('DQG-033', 'Multi-fact integration'),
  DqgContractRule('DQG-034', 'Criterion matrix complete'),
  DqgContractRule('DQG-035', 'KEY complete on all material criteria'),
  DqgContractRule('DQG-036', 'Each distractor fails decisive criterion'),
  DqgContractRule('DQG-037', 'KEY greater than D1 proof'),
  DqgContractRule('DQG-038', 'KEY greater than D2 proof'),
  DqgContractRule('DQG-039', 'KEY greater than D3 proof'),
  DqgContractRule('DQG-040', 'Counterfactual minimal and plausible'),
  DqgContractRule('DQG-041', 'Grammar/type/level parity'),
  DqgContractRule('DQG-042', 'Specificity/detail parity'),
  DqgContractRule('DQG-043', 'Surface metrics and no length cue'),
  DqgContractRule('DQG-044', 'Terminology/units/precision/condition parity'),
  DqgContractRule('DQG-045', 'No linguistic/position cue'),
  DqgContractRule('DQG-046', 'No keyword leakage'),
  DqgContractRule('DQG-047', 'No certainty shortcut'),
  DqgContractRule('DQG-048', 'No nontechnical elimination shortcut'),
  DqgContractRule('DQG-049', 'No unstated KEY assumption'),
  DqgContractRule('DQG-050', 'Assumptions documented and controlled'),
  DqgContractRule('DQG-051', 'No assumption-created equivalence'),
  DqgContractRule('DQG-052', 'Authoritative source supports KEY'),
  DqgContractRule('DQG-053', 'Sources support distractor rejection'),
  DqgContractRule('DQG-054', 'No unsupported microscopic distinction'),
  DqgContractRule('DQG-055', 'Ambiguity firewall'),
  DqgContractRule('DQG-056', 'SME rejection proof for every distractor'),
  DqgContractRule('DQG-057', 'No duplicate/equivalent options'),
  DqgContractRule('DQG-058', 'Numerical provenance and consistency'),
  DqgContractRule('DQG-059', 'Answer key independently verified'),
  DqgContractRule('DQG-060', 'Stem information sufficient'),
  DqgContractRule('DQG-061', 'Tests intended competency not trivia'),
  DqgContractRule('DQG-062', 'Wrong-level correctness controlled'),
  DqgContractRule('DQG-063', 'Sophistication parity when applicable'),
  DqgContractRule('DQG-064', 'Aggregate fail-closed publication gate'),
];
